"use server";

import { redirect } from "next/navigation";
import { createClient } from "@gams/lib/supabase/server";
import { z } from "zod";

const schema = z.object({
  // auth
  email: z.string().email("Valid email required"),
  password: z.string().min(8, "Password must be at least 8 characters"),
  confirm_password: z.string(),
  // company basics
  legal_name: z.string().min(3, "Legal company name required"),
  trade_name: z.string().optional(),
  cin: z.string().optional(),
  gstin: z
    .string()
    .regex(
      /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/,
      "Invalid GSTIN format"
    ),
  pan: z
    .string()
    .regex(/^[A-Z]{5}[0-9]{4}[A-Z]{1}$/, "Invalid PAN format"),
  msme_number: z.string().optional(),
  is_msme: z.string().optional(),
  msme_category: z.string().optional(),
  // contact
  contact_email: z.string().email("Valid contact email required"),
  contact_mobile: z
    .string()
    .regex(/^[6-9][0-9]{9}$/, "Valid 10-digit mobile required"),
  website: z.string().url("Enter valid URL with https://").optional().or(z.literal("")),
  // address
  addr_line1: z.string().min(5, "Address required"),
  addr_line2: z.string().optional(),
  addr_city: z.string().min(2, "City required"),
  addr_district: z.string().min(2, "District required"),
  addr_state: z.string().length(2, "Select state"),
  addr_pincode: z
    .string()
    .regex(/^[1-9][0-9]{5}$/, "Valid pincode required"),
  // bank
  bank_name: z.string().min(2, "Bank name required"),
  bank_ifsc: z
    .string()
    .regex(/^[A-Z]{4}0[A-Z0-9]{6}$/, "Invalid IFSC code"),
  bank_account_no: z.string().min(9, "Account number required"),
}).refine((d) => d.password === d.confirm_password, {
  message: "Passwords do not match",
  path: ["confirm_password"],
});

export async function registerCompanyAction(formData: FormData) {
  const raw = Object.fromEntries(formData.entries());
  const parsed = schema.safeParse(raw);

  if (!parsed.success) {
    const firstError = parsed.error.errors[0];
    redirect(`/register?error=${encodeURIComponent(firstError.message)}`);
  }

  const d = parsed.data;
  const supabase = await createClient();

  // 1. Create auth user
  const { data: authData, error: signUpError } = await supabase.auth.signUp({
    email: d.email,
    password: d.password,
    options: {
      data: { portal: "company", legal_name: d.legal_name },
    },
  });

  if (signUpError) {
    redirect(`/register?error=${encodeURIComponent(signUpError.message)}`);
  }

  if (!authData.user) {
    redirect("/register?error=Account+creation+failed");
  }

  // 2. Insert company (status = pending_review)
  const { data: company, error: companyError } = await supabase
    .from("companies")
    .insert({
      legal_name: d.legal_name,
      trade_name: d.trade_name || null,
      cin: d.cin || null,
      gstin: d.gstin,
      pan: d.pan.toUpperCase(),
      msme_number: d.msme_number || null,
      is_msme: d.is_msme === "yes",
      msme_category: d.msme_category || null,
      contact_email: d.contact_email,
      contact_mobile: d.contact_mobile,
      website: d.website || null,
      registered_address: {
        line1: d.addr_line1,
        line2: d.addr_line2 || "",
        city: d.addr_city,
        district: d.addr_district,
        state: d.addr_state,
        pincode: d.addr_pincode,
      },
      bank_account: {
        bank_name: d.bank_name,
        ifsc: d.bank_ifsc.toUpperCase(),
        account_no_masked: `XXXX${d.bank_account_no.slice(-4)}`,
      },
      // company_code generated by DB trigger or admin — placeholder for now
      company_code: `PENDING-${Date.now()}`,
    })
    .select("id")
    .single();

  if (companyError) {
    redirect(`/register?error=${encodeURIComponent(companyError.message)}`);
  }

  // 3. Link user to company
  const { error: linkError } = await supabase.from("company_users").insert({
    company_id: company.id,
    user_id: authData.user.id,
    is_primary: true,
  });

  if (linkError) {
    redirect(`/register?error=${encodeURIComponent(linkError.message)}`);
  }

  redirect("/dashboard?registered=1");
}
