-- =============================================================================
-- GAMS — Government Asset Management System
-- Migration 002: Supabase Storage Buckets + Policies
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Buckets
-- ---------------------------------------------------------------------------

-- Company & institution uploaded documents (private)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'gams-documents',
  'gams-documents',
  false,
  20971520,  -- 20 MB
  ARRAY[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
ON CONFLICT (id) DO NOTHING;

-- User avatars (public CDN — no auth required to read)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'gams-avatars',
  'gams-avatars',
  true,
  5242880,  -- 5 MB
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;

-- QR code label exports (private, generated by batch_jobs)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'gams-exports',
  'gams-exports',
  false,
  104857600,  -- 100 MB for large CSV/ZIP exports
  ARRAY[
    'text/csv',
    'application/zip',
    'application/pdf'
  ]
)
ON CONFLICT (id) DO NOTHING;

-- Asset condition photos uploaded by volunteers / inspectors
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'gams-photos',
  'gams-photos',
  false,
  10485760,  -- 10 MB per photo
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/heic']
)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. Storage RLS Policies — gams-documents
-- ---------------------------------------------------------------------------

-- Company reps can upload to their own company folder
CREATE POLICY "company_docs_upload"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'gams-documents'
    AND (storage.foldername(name))[1] = 'company'
    AND auth.uid() IN (
      SELECT user_id FROM public.company_users
    )
  );

-- Company reps can read their own company's documents
CREATE POLICY "company_docs_read"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'gams-documents'
    AND (storage.foldername(name))[1] = 'company'
    AND (
      -- Company rep reading their own docs
      auth.uid() IN (
        SELECT cu.user_id
        FROM public.company_users cu
        WHERE cu.company_id::text = (storage.foldername(name))[2]
      )
      OR
      -- Management portal admin reading any company docs
      EXISTS (
        SELECT 1 FROM public.user_profiles up
        WHERE up.id = auth.uid()
          AND up.role IN ('super_admin', 'gov_admin', 'auditor')
      )
    )
  );

-- Institution reps can upload to their own institution folder
CREATE POLICY "institution_docs_upload"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'gams-documents'
    AND (storage.foldername(name))[1] = 'institution'
    AND auth.uid() IN (
      SELECT user_id FROM public.institution_users
    )
  );

-- Institution reps can read their own institution's documents
CREATE POLICY "institution_docs_read"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'gams-documents'
    AND (storage.foldername(name))[1] = 'institution'
    AND (
      auth.uid() IN (
        SELECT iu.user_id
        FROM public.institution_users iu
        WHERE iu.institution_id::text = (storage.foldername(name))[2]
      )
      OR
      EXISTS (
        SELECT 1 FROM public.user_profiles up
        WHERE up.id = auth.uid()
          AND up.role IN ('super_admin', 'gov_admin', 'auditor')
      )
    )
  );

-- Management portal can delete documents during review (e.g. stale uploads)
CREATE POLICY "admin_docs_delete"
  ON storage.objects FOR DELETE TO authenticated
  USING (
    bucket_id = 'gams-documents'
    AND EXISTS (
      SELECT 1 FROM public.user_profiles up
      WHERE up.id = auth.uid()
        AND up.role IN ('super_admin', 'gov_admin')
    )
  );

-- ---------------------------------------------------------------------------
-- 3. Storage RLS Policies — gams-avatars (public bucket, own upload only)
-- ---------------------------------------------------------------------------

-- Any authenticated user can upload their own avatar
-- Path convention: avatars/{user_id}.jpg
CREATE POLICY "avatar_upload_own"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'gams-avatars'
    AND (storage.filename(name)) LIKE auth.uid()::text || '%'
  );

-- Public read (bucket is public so no policy needed for reading, but
-- restrict upsert/delete to owner)
CREATE POLICY "avatar_update_own"
  ON storage.objects FOR UPDATE TO authenticated
  USING (
    bucket_id = 'gams-avatars'
    AND (storage.filename(name)) LIKE auth.uid()::text || '%'
  );

CREATE POLICY "avatar_delete_own"
  ON storage.objects FOR DELETE TO authenticated
  USING (
    bucket_id = 'gams-avatars'
    AND (storage.filename(name)) LIKE auth.uid()::text || '%'
  );

-- ---------------------------------------------------------------------------
-- 4. Storage RLS Policies — gams-exports
-- ---------------------------------------------------------------------------

-- Management admins and warehouse officers can read/write exports
CREATE POLICY "exports_management_rw"
  ON storage.objects FOR ALL TO authenticated
  USING (
    bucket_id = 'gams-exports'
    AND EXISTS (
      SELECT 1 FROM public.user_profiles up
      WHERE up.id = auth.uid()
        AND up.role IN ('super_admin', 'gov_admin', 'warehouse_officer', 'event_manager')
    )
  )
  WITH CHECK (
    bucket_id = 'gams-exports'
    AND EXISTS (
      SELECT 1 FROM public.user_profiles up
      WHERE up.id = auth.uid()
        AND up.role IN ('super_admin', 'gov_admin', 'warehouse_officer', 'event_manager')
    )
  );

-- File initiator can read their own export
CREATE POLICY "exports_own_read"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'gams-exports'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- ---------------------------------------------------------------------------
-- 5. Storage RLS Policies — gams-photos
-- ---------------------------------------------------------------------------

-- Volunteers and inspectors can upload photos (path: {event_id}/{instance_id}/...)
CREATE POLICY "photos_field_upload"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'gams-photos'
    AND EXISTS (
      SELECT 1 FROM public.user_profiles up
      WHERE up.id = auth.uid()
        AND up.role IN ('volunteer', 'inspector', 'warehouse_officer', 'event_manager', 'gov_admin', 'super_admin')
    )
  );

-- Management portal can read all condition photos
CREATE POLICY "photos_management_read"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'gams-photos'
    AND EXISTS (
      SELECT 1 FROM public.user_profiles up
      WHERE up.id = auth.uid()
        AND up.role IN ('super_admin', 'gov_admin', 'event_manager', 'inspector', 'auditor', 'warehouse_officer')
    )
  );

-- =============================================================================
-- Done
-- =============================================================================
